- .gitignore
- package.json
- src/pages/Routes.tsx
- tsconfig.json
- vite.config.ts
- yarn.lock
- closes #3 
- 절대경로 추가
- 라우터 코드 정리
> #3 type: chore 프로젝트세팅 구현

- .gitignore
- package.json
- yarn.lock
- closes #5 
- 개발 환경 실행 명령어 추가
- package.json - `npm start`
- `@type/node` devDependencies 이동
> #5 chore: package.json 명령어 추가 및 컴파일 시 자동 오픈

- package.json
- src/components/Modal/ModalItem/ModalButton.tsx
- src/components/Modal/ModalItem/ModalInput.tsx
- src/components/Modal/ModalItem/ModalText.tsx
- src/components/Modal/ModalItem/index.tsx
- src/components/Modal/ModalItem/modalItem.module.scss
- src/components/Modal/index.tsx
- src/components/Modal/modal.module.scss
- src/pages/ModalTest/ModalTest.tsx
- src/pages/Routes.tsx
- yarn.lock
- #1 
- 공유 모달 틀 구현
- 공유 모달 레이블 구현
- 공유 모달 인풋 구현
- 공유 모달 버튼 구현
- 테스트 페이지 작성 (ModalTest)
- classnames 라이브러리 설치
components
ㄴModal
ㄴModalItem  // 모달 내부 레이블, 인풋, 버튼 
ㄴindex.tsx      // 모달 틀
> #1 feat: 모달 공유 컴포넌트 구현

- src/pages/ModalTest/ModalCallTest.tsx
- src/pages/Nickname/EditNickname.tsx
- src/pages/Nickname/MakeNickname.tsx
- closes #19 
- 닉네임 추가 모달 레이아웃 구현
- 닉네임 수정 모달 레이아웃 구현
- env 로 인한 cherry-pick PR 재업로드입니다.
> #19 feat : 닉네임 추가/수정 레이아웃 구현 완료 - 재업로드

- src/components/Modal/ModalItem/modalItem.module.scss
- src/pages/ChangeRoll/ChangeShareRoll.tsx
- src/pages/ChangeRoll/DeleteRoll.tsx
- src/pages/ChangeRoll/EditRoll.tsx
- src/pages/ChangeRoll/editRoll.module.scss
- src/pages/CreateRoll/contents/CreateShareRoll.tsx
- src/pages/CreateRoll/index.tsx
- src/pages/ModalTest/ModalCallTest.tsx
- src/styles/pages/_shareRoll.module.scss
- closes #22 
- 롤링페이퍼 수정 모달 레이아웃
- 롤링페이퍼 링크 공유 모달 레이아웃
- 롤링페이퍼 삭제 모달 레이아웃
- env 로 인한 cherry-pick PR 재업로드입니다.
> #22 feat: 롤링페이퍼 변경 모달 레이아웃 구현 완료 - 재업로드

- src/pages/MyPage/MyPageItem/MyPageDropdown/index.tsx
- src/pages/MyPage/MyPageItem/MyPageDropdown/myPageDropdown.module.scss
- src/pages/MyPage/MyPageItem/index.tsx
- src/pages/MyPage/MyPageItem/myPageItem.module.scss
- src/pages/MyPage/index.tsx
- src/pages/MyPage/myPage.module.scss
- closes #32 
- 마이페이지 내 드롭다운 레이아웃
- [나만보기], [모두보기] 토글 추가
> #32 feat : 마이페이지 드롭다운 레이아웃 구현

- src/api/index.ts
- src/api/tokenStore.ts
- src/api/user.ts
- src/components/buttons/KakaoButton.tsx
- src/pages/Home/index.tsx
- src/pages/KakaoRedirect/index.tsx
- src/pages/Routes.tsx
- vercel.json
- closes #20 
- base api url vercel app 등록
- vercel spa 라우터 설정
- 카카오 로그인 토큰 저장 및 리다이렉트
- axios 요청에 토큰 담기
-
> #20 feat : 카카오 로그인 (+ api 기본 세팅)

- src/pages/MyPage/MyPageItem/index.tsx
- src/pages/MyPage/MyPageItem/myPageItem.module.scss
- src/pages/MyPage/index.tsx
- src/pages/MyPage/myPage.module.scss
- closes #47
- 마이페이지 `img` 태그 삭제
- React Component 로 import 해서 아이콘 컴포넌트로 적용
- 코드 변경 사항에 따른 스타일 추가 작업
> #47 fix : 마이페이지 빌드 환경에서 이미지 깨짐 현상 수정

- src/api/index.ts
- src/api/rollingpaper.ts
- src/components/rollingpaper/Card.tsx
- src/components/rollingpaper/CardModal.tsx
- src/components/rollingpaper/GotoLoginButton.tsx
- src/components/rollingpaper/MoveableSticker.tsx
- src/components/rollingpaper/RndSticker.tsx
- src/components/rollingpaper/StickerModifyContent.tsx
- src/components/rollingpaper/rollingpaper.module.scss
- src/pages/RollingPaper.tsx
- src/pages/Routes.tsx
- src/styles/colors.scss
- src/utils/rollingPaper/Card.type.ts
- src/utils/rollingPaper/Sticker.type.ts
- src/utils/rollingPaper/cardDummy.ts
- src/utils/rollingPaper/stickerDummy.ts
- closes #45 
- 스티커 fetch, update
- 롤링페이퍼 카드 fetch 
- 로그인 이동 버튼 생성
- svg 버튼 cursor 수정
- uuid로 paper Id 가져오는 작업 필요
> #45 feat: 롤링페이퍼 페이지 api 연동 완료  

- src/api/rollingpaper.ts
- src/components/rollingpaper/EditorButton.tsx
- src/components/rollingpaper/StickerModifyContent.tsx
- src/components/rollingpaper/rollingpaper.module.scss
- src/pages/RollingPaper.tsx
- src/styles/components/_header.scss
- closes #53
- 헤더 스타일 수정
- 스티커 content 스타일 수정 (아무 카드가 없는 경우) 
- url로 paper Id 가져온 후 api 사용하도록 수정
- console.log 삭제
- 얌얌 작업 완료 기타 수정 문의 바랍니당
> url로 paper Id fetch

- src/api/rollingpaper.ts
- src/components/rollingpaper/StickerContent.tsx
- src/components/rollingpaper/StickerModifyContent.tsx
- src/components/rollingpaper/rollingpaper.module.scss
- src/pages/RollingPaper.tsx
- closes #57 
- transition으로 깜박이는 문제 해결
- api 업데이트 반영 (키 값 변경) 
- useCallback 수정
> #57 bug: 스티커 깜박이는 문제, 처음 sticker 반영 안되는 문제 해결

- src/components/rollingpaper/StickerModal.tsx
- src/components/rollingpaper/StickerModifyContent.tsx
- src/pages/RollingPaper.tsx
- closes #59 
- react router query로 modify mode 값 초기화 
- createportal dom 생성 에러 해결 
- sending 버튼 연결 필요 (레몬 작업중)
- 레몬 url은 'rollingpaper/{paperurl}?sticker-mode=true 로 주면 됩니다.
> #59 sending 페이지에서 스티커로 꾸며보기 버튼 클릭 -> modify mode로 바로 연결

- src/pages/MyPage/MyPageItem/MyPageDropdown/index.tsx
- src/pages/MyPage/MyPageItem/MyPageDropdown/myPageDropdown.module.scss
- src/pages/MyPage/MyPageItem/index.tsx
- src/pages/MyPage/MyPageItem/myPageItem.module.scss
- src/pages/MyPage/index.tsx
- src/styles/abstracts/_responsive.scss
- closes #56
- 드롭다운 리스트의 나만보기 및 전체보기 토글과 svg 아이콘 기능 분리
- 반응형 믹스인 추가
- 의미에 맞는 변수 네이밍 변경 ( user -> paper )
- 롤링페이퍼(Roll) 간에 드롭다운 겹침 문제 해결
- 반응형 관련 믹스인 추가된 것은 `src/styles/abstracts/_responsive.scss` 파일을 참고하시거나 저에게 문의 주세요~
> #56 refactor : 드롭다운 기능 분리 및 중첩 현상 문제 해결

- src/assets/index.ts
- closes #65 
- svg icon export 파일 생성
- 우선 파일만 만들어두고, 추후 조금씩 적용하는 방법이 좋을 것 같습니다.
- 사용 방법은 파일 내부에 적어두었습니다.
> #65 refactor: svg icon export 파일 생성

- index.html
- src/config/commonLink.ts
> #80 feat: 프론트 도메인 변경

- src/pages/MyPage/MyPageItem/index.tsx
- src/pages/MyPage/index.tsx
- src/utils/rollingPaper/paper.ts
- closes #83
- 마이페이지 스크롤 미동작 버그 수정
- 롤링페이퍼 페이지의 오픈일자가 현재 일자를 경과한 경우 열리지 않는 버그 수정
> #83 fix: 마이페이지 스크롤, 오픈일자 버그 수정

- src/pages/Editor/index.tsx
- closes #84
- 롤링페이퍼 작성자 닉네임 기입하지 않으면 익명처리
-
> #84 feat: 롤링페이퍼 작성 닉네임 없을 시 익명 처리

- src/api/user.ts
- src/components/Modal/ModalItem/modalButton.module.scss
- src/components/Modal/ModalItem/modalInput.module.scss
- src/pages/ChangeRoll/EditRoll.tsx
- src/pages/CreateRoll/contents/MakeRoll.tsx
- src/pages/CreateRoll/index.tsx
- src/pages/ErrorHandling/NotPermission.tsx
- src/pages/Nickname/EditNickname.tsx
- src/pages/Nickname/MakeNickname.tsx
- src/pages/Routes.tsx
- src/pages/Sending/sending.module.scss
- src/pages/ShareRoll/ShareRollItem/shareRollItem.module.scss
- src/styles/core/_reset.scss
- src/utils/rollingPaper/paper.ts
- closes #93 
-  sending 모바일 height 반응형
-  403 error page
-  오늘날짜 클릭 막기 (내일부터 입력가능하도록)
-  롤링페이퍼 타이틀 빈값 → 빨강색 에러메시지
-  클립보드 클릭시 아이콘 색 변하도록
-  input 클릭했을 때 외곽선 삭제
-  모달 버튼 120px로 변경
-  클립보드 버튼 클릭시 클릭 효과 추가
> #93 feat: 반응형 조절

- src/components/rollingpaper/container/Content.tsx
> #99 bug: 무한 호출 에러 수정

- src/config/commonLink.ts
> #109 fix: vite build env import 오류 수정

- src/components/layout/Header.tsx
- closes #111 
- nickname 없을 때 모달 true로 변경
- nickname 없을 경우 클릭할 메시지 임시 추가
> #111 fix: nickname 없을 때 체크방식 변경

- src/components/layout/Layout.tsx
- src/components/rollingpaper/button/button.module.scss
- src/components/rollingpaper/container/Content.tsx
- src/components/rollingpaper/container/rollingpaper.module.scss
- src/pages/Home/index.module.scss
- src/pages/RollinPaper/RollingPaper.tsx
- src/styles/colors.scss
- src/styles/components/_header.scss
- src/styles/layout/_layout.scss
- src/styles/pages/_home.scss
- src/styles/pages/_rollingpaper.scss
> #103 자잘한 버그 수정

- src/pages/Editor/components/RadioGroup.tsx
- src/pages/Editor/components/Select.tsx
- closes #118 
- 에디터 리스트 항목 key 수정
-
> #118 fix: 에디터 리스트 항목 key 수정

- index.html
> #121 fix: 모바일 메타태그 변경

- src/pages/BlockRoll/index.tsx
- closes #123 
- block roll 모달 닫기 이벤트 추가
> #123 fix: 모달 닫기 이벤트 추가

- src/api/user.ts
- closes #125
- 닉네임 API response 방식 수정
> #125 fix: 닉네임 API response 방식 수정

- src/api/rollingpaper.ts
- src/pages/Editor/editor.module.scss
- src/pages/Editor/index.tsx
- closes #128 
- 카드 생성 api 응답 변경에 따른 처리 코드 수정
- 에디터 디자인 수정
-
> #128 fix: 롤링페이퍼 카드 생성 api 응답 처리 수정 및 에디터 디자인 수정

- src/api/rollingpaper.ts
- closes #120 
- api 변경에 대한 수정
- 이미지 버튼 추가
> 스티커 api 변경에 대한 수정

- src/api/user.ts
- src/assets/index.ts
- src/components/Modal/ModalItem/modalButton.module.scss
- src/components/Modal/modal.module.scss
- src/components/rollingpaper/button/HomeButton.tsx
- src/components/rollingpaper/button/button.module.scss
- src/components/rollingpaper/card/card.module.scss
- src/components/rollingpaper/container/Content.tsx
- src/components/rollingpaper/container/StickerModifyContent.tsx
- src/components/rollingpaper/container/rollingpaper.module.scss
- src/components/rollingpaper/modal/modal.module.scss
- src/components/rollingpaper/sticker/MoveableSticker.tsx
- src/pages/RollinPaper/RollingPaper.tsx
- src/pages/Sending/sending.module.scss
- src/styles/layout/_layout.scss
- src/styles/pages/_rollingpaper.scss
- closes #131 
- vh -> %
- console.log 제거
- 카드 자세히보기 스크롤 고침
- 롤링페이퍼 로고 홈으로 가기 추가
- 첫 랜더링 zoom 설정
- 스티커 생성위치 좀 더 알기 쉽게 설정
- 카드 텍스트 break 수정
> #131 fix: QA 버그 수정 및 기능 추가

- src/pages/MyPage/MyPageItem/MyPageDropdown/myPageDropdown.module.scss
- src/pages/MyPage/MyPageItem/OpenState.tsx
- src/pages/MyPage/MyPageItem/index.tsx
- src/pages/MyPage/MyPageItem/myPageItem.module.scss
- src/pages/MyPage/MyPageItem/openState.module.scss
- src/pages/MyPage/index.tsx
- src/pages/MyPage/myPage.module.scss
- src/styles/colors.scss
- closes #116 
- 마이 페이지 전체 레이아웃 컴포넌트 수정
- 페이퍼 내 리스트 아이템 컴포넌트 수정
- 상태를 표시하기 위한 컴포넌트 추가
> #116 feat : 마이페이지 UI 전면 수정

- src/pages/Editor/editor.module.scss
- src/pages/Editor/index.tsx
- src/pages/Home/index.tsx
- closes #139 
- 에디터 다크모드 적용 (롤링페이퍼와 통일)
- 로그인 상태 시 홈 -> 마이페이지 리다이렉트
-
> #139 feat: 에디터 다크모드 및 로그인 상태 시 리다이렉트

- src/pages/MyPage/MyPageItem/MyPageDropdown/myPageDropdown.module.scss
- src/pages/MyPage/MyPageItem/OpenState.tsx
- src/pages/MyPage/MyPageItem/index.tsx
- src/pages/MyPage/MyPageItem/myPageItem.module.scss
- src/pages/MyPage/MyPageItem/openState.module.scss
- src/pages/MyPage/index.tsx
- src/pages/MyPage/myPage.module.scss
- closes #141 
- 페이지 드롭다운 버튼 영역 넓히기
- 전체 레이아웃의 높이 조정 (테두리 짤림 문제 수정)
- 마이페이지 컨테이너 상단 패딩 조정
- 페이지 내 전체 폰트 사이즈, 컨텐츠의 크기, 높이 조정
- 리스트의 드롭다운 버튼 조작 시, 리스트 전체에 색깔이 들어오는 문제 수정 (hover 제거)
- 플로팅 메세지 제거 (모달 대체)
> #141 style: 마이페이지 스타일 수정

- src/pages/Ads/index.tsx
> Fix: 애드블록 탐지 테스트

- package.json
- src/hooks/index.tsx
- src/hooks/useAdBlockDetect.tsx
- src/pages/Sending/Sending.tsx
> #148 fix: 애드블록 탐지 라이브러리 추가

- src/pages/Home/index.tsx
- closes #155 
- 홈에서 토큰 존재 시, 마이페이지로 리다이렉트 해주는 코드 제거
-
> #155 fix: 로그인 상태에서 홈에서 마이페이지 리다이렉트 삭제

- src/pages/MyPage/MyPageItem/MyPageDropdown/myPageDropdown.module.scss
- src/pages/MyPage/MyPageItem/index.tsx
- src/pages/MyPage/myPage.module.scss
- closes #153 
- 마이페이지 드롭다운이 생성 버튼에 덮여지는 문제 수정
- 파일 내 사용하지 않는 모듈의 코드 제거
- 드롭다운, 롤링페이퍼 생성 버튼 위치 조정
> #153 style : 마이페이지 드롭다운 스타일 수정

- index.html
- src/assets/favicon.svg
- src/components/rollingpaper/button/button.module.scss
- src/pages/ShareRoll/ShareRollItem/index.tsx
- closes #159
- 파비콘 추가
- 로고 블러처리 제거
- 이미지 저장 임시 블록처리
> fix: 기타 사항 수정

- src/pages/MyPage/MyPageItem/MyPageDropdown/myPageDropdown.module.scss
- src/pages/MyPage/MyPageItem/myPageItem.module.scss
- src/pages/MyPage/myPage.module.scss
- closes #162 
- 마이페이지 반응형 스타일 제거
> #162 style : 마이페이지 반응형 스타일 수정

- src/utils/rollingPaper/dateDiffFormat.ts
> fix: 시간 오류 수정

- src/pages/CreateRoll/contents/MakeRoll.tsx
- src/pages/Home/index.module.scss
- src/pages/MyPage/MyPageItem/myPageItem.module.scss
- src/pages/MyPage/myPage.module.scss
- src/utils/rollingPaper/dateDiffFormat.ts
- closes #164 
- width 변경, 한국시간 조정
> #164 시간 변경, 한국시간 +9시간 빼기

- src/pages/CreateRoll/contents/MakeRoll.tsx
- src/pages/Home/index.module.scss
- src/pages/MyPage/MyPageItem/myPageItem.module.scss
- src/pages/MyPage/myPage.module.scss
- src/utils/rollingPaper/dateDiffFormat.ts
[PR 작성 시 기본 제목 (작성 후 이 줄은 지워주세요 😀) -> #(issue number) type: 작업 제목]
- closes `#작업한 issue number`
- 본인이 작업한 내용
- 코드리뷰때 이런걸 봐줬으면 좋겠다?
- 모두가 알면 좋을 지식, 해결 과정
- 구조 변화 등
> dev to main

- src/utils/common/url.ts
> #169 fix: ga key 수정

- src/components/rollingpaper/container/OpenDate.tsx
- src/pages/BlockRoll/index.tsx
- src/pages/MyPage/MyPageItem/OpenState.tsx
- src/pages/MyPage/index.tsx
- closes #178 
- 오픈 => 마감 단어 변경
> #178 fix: 오픈 -> 마감 단어 변경

- src/pages/SettingRoll/settingRoll.module.scss
- src/styles/components/_header.scss
- closes #173 
- 설정 디자인 수정 - border 처리, height, 여백 조절 등.
> #173 style: 설정 스타일 수정
